### ISSUE TITLE
[TOC] Table of Contents Issues

### ISSUE THREAD

**Issue by mmcky** [executablebooks/jupyterbook-latex#23]
**Describe the bug**

@AakashGfude I am still getting duplicate content in the TOC

![image](https://user-images.githubusercontent.com/8263752/102735810-79f2a580-4397-11eb-9c83-da9f35eac79c.png)

- [ ] Section 5 is a repeat of Section 1. 

Part 1 should only have `7` chapters

```
- part: Introduction to Python
  chapters:
    - file: about_py
    - file: getting_started
    - file: python_by_example
    - file: functions
    - file: python_essentials
    - file: oop_intro
    - file: python_oop
```

and the file I am building has `11`

**To Reproduce**

Build pdf for `lecture-python-programming.myst::jupyterbook-latex` using:

```
jb build lectures --builder=pdflatex
```
